import { OnInit, OnDestroy } from '@angular/core';
import { DragulaService } from 'ng2-dragula';
import { MhDynamicFormElementConfig } from './dynamic-form.entity';
import { MatDialog } from '@angular/material';
import { MhDynamicLoaderService } from './dynamic-loader.service';
export declare class MhFormDesignComponent implements OnInit, OnDestroy {
    private dialog;
    private dragulaService;
    private notificationService;
    private loaderService;
    panelForm: any;
    controlTag: string;
    elementTag: string;
    h3Name: string;
    bagName: string;
    options: any;
    selectControls: any[];
    controls: MhDynamicFormElementConfig[];
    elements: any[];
    nameArr: string[];
    selectedindex: number;
    readonly valid: boolean;
    dragOpt: any;
    constructor(dialog: MatDialog, dragulaService: DragulaService, notificationService: any, loaderService: MhDynamicLoaderService);
    ngOnInit(): void;
    getDemo(): any[];
    registerDrop(): void;
    validate(): boolean;
    syncNameArr(): void;
    elementClick(element: any): void;
    getElementIndex(name: string): number;
    open(type: string, field: string): void;
    checkDefault(type: string): boolean;
    checkMaxlength(type: string): boolean;
    checkMinMax(type: string): boolean;
    checkPattern(type: string): boolean;
    checkDatasource(type: string): boolean;
    checkDictionary(type: string): boolean;
    checkControls(type: string): boolean;
    checkSelectFIeld(type: string): boolean;
    checkMultiple(type: string): boolean;
    checkUploadAccept(type: string): boolean;
    checkIcon(type: string): boolean;
    checkSuffix(type: string): boolean;
    checkDepth(type: string): boolean;
    checkEntryWidth(type: string): boolean;
    ngOnDestroy(): void;
}
