import { OnInit, EventEmitter, ChangeDetectorRef } from '@angular/core';
import { TdDataTableService, IPageChangeEvent } from '@covalent/core';
import { HttpUtilService } from '../../services/index';
import { NativeDateAdapter, DateAdapter } from '@angular/material';
export declare class WeekViewComponent implements OnInit {
    private _dataTableService;
    private httpUtilService;
    private cdr;
    ddCampus: any;
    select: EventEmitter<any>;
    viewDate: Date;
    headColor: string;
    headBgColor: string;
    subColor: string;
    subBgColor: string;
    rowHeadColor: string;
    rowHeadBgColor: string;
    color: {
        [key: string]: any;
    };
    TIME: any[];
    STATUS: any[];
    days: any[];
    events: any[];
    map: any[];
    places: any[];
    cols: number;
    filteredData: any[];
    filteredTotal: number;
    fromRow: number;
    currentPage: number;
    pageSize: number;
    constructor(_dataTableService: TdDataTableService, httpUtilService: HttpUtilService, cdr: ChangeDetectorRef, dateAdapter: DateAdapter<NativeDateAdapter>);
    detectChanges(): void;
    ngOnInit(): void;
    init(): void;
    dateChange(date: any): void;
    preWeek(): void;
    nextWeek(): void;
    page(pagingEvent: IPageChangeEvent): void;
    filter(): void;
    initMap(): void;
    findRowIndex(place: any): number;
    findDateIndex(date: number | Date | string): number;
    findTimeIndex(time: number | Date | string): number;
    getColor(rowIndex: number, dateIndex: number, timeIndex: number): string;
    getTooltip(rowIndex: number): string;
    apply(rowIndex: number, dateIndex: number, timeIndex: number): void;
}
